import type { Metadata } from "next";
import { Container } from "@mui/material";
import AppBar from "@/component/AppBar/AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppBar />
        <Container maxWidth="lg">{children}</Container>
      </body>
    </html>
  );
}
